### ISSUE TITLE
fix readme - change npm instruction to yarn 

### ISSUE THREAD

**Issue by tesla809** [strenev/ipfs-proof-of-existence#3]
I see that yarn.lock is in the file. To avoid conflict between `yarn.lock` and `npm.lock`, either:
1. ask user to use `yarn`
2. ask user to delete `yarn.lock` file first, then run `npm install`

**Comment by tesla809** [comment]
Or if you pick npm, remove `yarn.lock` files to avoid conflicts.

**Comment by strenev** [comment]
Done, now only npm is used.
