### ISSUE TITLE
add instructions on how to test in developement

### ISSUE THREAD

**Issue by tesla809** [strenev/ipfs-proof-of-existence#5]
add instructions on how to test in development.

### Build and run project locally
Backo smart contracts are developed using Truffle. The frontend client is using React. The following steps assume you have Node, npm/yarn, truffle and ganache-cli installed.

#### Install all the dependencies of the project
```
yarn install
```

#### Run a local blockchain
```
ganache-cli -p 8545
```
Specifying the blockTime is important as Backo smart contracts contain time-dependent logic

#### Compile smart contracts
```
truffle compile
```

#### Run migrations
```
truffle migrate --reset --network development
```

#### Start local frontend client-server 
```
npm start
```

### Testing

Tests can be run with the command
```
truffle test
```

**Comment by strenev** [comment]
Also added them under the test section in the readme.
