### ISSUE TITLE
add flag to include or exclude deployment of IPFSProofOfExistenceTestable.sol based on dev environment

### ISSUE THREAD

**Issue by tesla809** [strenev/ipfs-proof-of-existence#6]
It's cumbersome to comment out IPFSProofOfExistenceTestable.sol based needing to deploy a dev environment (local testnet) or not. 

Adding in a flag that checks if deploying to local or not, would be better.

**Comment by strenev** [comment]
Totally agree. Added a check to deploy the testable contract only in case we are using the development network.
