### ISSUE TITLE
testing does not work - please fix

### ISSUE THREAD

**Issue by tesla809** [strenev/ipfs-proof-of-existence#7]
Ran `truffle test` and got an error
`Error: Cannot find module '@truffle/hdwallet-provider'`

The issue is because:
1. no package.json file to install `@truffle/hdwallet-provider`
some people will not have global @truffle/hdwallet-provider installed
2. does not deploy. Need to uncomment lines that exclude`IPFSProofOfExistenceTestable.sol`

**Comment by strenev** [comment]
Added a separate package.json in the route folder for installing the @truffle/hdwallet-provider and @openzeppelin/contracts.
Also fixed the deployment issue as described in issue #6
